
const defaults={systemName:"AM2 PACS",institutionName:"AM2 Soluções",leftPanelImage:"./left-panel-approved.jpg?v=20260827-EXATO",primaryColor:"#0A78E8",primaryDark:"#073F79",welcomeTitle:"Bem-vindo(a) de volta!",welcomeText:"Entre com suas credenciais para acessar o sistema.",showForgotPassword:true,forgotPasswordUrl:"#",showPoweredBy:true,company:"AM2 Soluções"};
const branding={...defaults,...(window.PACS_BRANDING||{})};
function hexToRgb(hex){const v=hex.replace("#","");const n=parseInt(v.length===3?v.split("").map(c=>c+c).join(""):v,16);return{r:(n>>16)&255,g:(n>>8)&255,b:n&255}}
function applyBranding(){const root=document.documentElement,rgb=hexToRgb(branding.primaryColor);root.style.setProperty("--primary",branding.primaryColor);root.style.setProperty("--primary-dark",branding.primaryDark);root.style.setProperty("--primary-rgb",`${rgb.r},${rgb.g},${rgb.b}`);document.title=branding.systemName;document.getElementById("brandExact").style.backgroundImage=`url("${branding.leftPanelImage}")`;document.getElementById("welcomeTitle").textContent=branding.welcomeTitle;document.getElementById("welcomeText").textContent=branding.welcomeText;document.getElementById("forgotArea").style.display=branding.showForgotPassword?"flex":"none";document.getElementById("forgotLink").href=branding.forgotPasswordUrl;document.getElementById("powered").style.visibility=branding.showPoweredBy?"visible":"hidden";document.getElementById("company").textContent=branding.company;document.getElementById("year").textContent=new Date().getFullYear()}
applyBranding();
const password=document.getElementById("password");
document.getElementById("togglePassword").addEventListener("click",()=>{password.type=password.type==="password"?"text":"password"});
document.getElementById("loginForm").addEventListener("submit",e=>{e.preventDefault();const username=document.getElementById("username").value.trim(),pass=password.value,error=document.getElementById("loginError");error.classList.remove("show");error.textContent="";if(!username||!pass){error.textContent="Informe usuário e senha.";error.classList.add("show");return}console.log("Login:",{username,password:"********"})});
